# Generated by Django 4.2.4 on 2023-08-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_connexion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
