# Generated by Django 4.2.4 on 2023-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_connexion', '0002_alter_utilisateurs_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
